#!/bin/bash
TUSER=ubuntu
TUSERHOME=/home/${TUSER}

# Install needed packages
add-apt-repository multiverse
set -e
apt-get update

apt-get install -y git bzr python-bzrlib lxc pastebinit apt-cacher-ng

# Create and set up my user and directories
if  ! id ${TUSER} ; then
    useradd -m -d ${TUSERHOME} ${TUSER}
fi

mkdir -p ${TUSERHOME}/.config

mkdir -p /var/lib/tarmac
chown ${TUSER}:${TUSER} /var/lib/tarmac

# Get tarmac and my configuration to deploy
juju-log "Getting tarmac configs from github"
[ -e ${TUSERHOME}/.config/tarmac ] && rm -rf ${TUSERHOME}/.config/tarmac || true
git clone -b personal-hexr git://github.com/codersquid/tarmac-configs.git ${TUSERHOME}/.config/tarmac

juju-log "Getting customized tarmac from github"
[ -e ${TUSERHOME}/tarmac ] && rm -rf ${TUSERHOME}/tarmac || true
git clone git://github.com/checkbox/tarmac.git ${TUSERHOME}/tarmac

juju-log "Installing upstart config file for tarmac-lander"
cp ${TUSERHOME}/.config/tarmac/tarmac-lander.conf /etc/init

